trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm test -- --code-coverage --watch=false
    ng build --prod
  displayName: 'npm install and build'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TESTS-*.xml'
  displayName: 'Publish Test Results'

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
  displayName: 'Publish Code Coverage Results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'angular-web-app'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'

- task: AzureCLI@1
  displayName: Az File Copy to Storage
  inputs:
    azureSubscription: $(azureSubscription)
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch \
        --destination \$web \
        --account-name "$(storageAccountName)" \
        --source "$(System.DefaultWorkingDirectory)/dist"
